services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 50M

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 50M

networks:
  backend:
    driver: bridge
    
volumes:
  postgres_data:
  app_data: